### PR TITLE
Update ru-ru (fixes)

### PR DESCRIPTION
**Pull request by iDolmatov**
Added newline/line break "`&#x000A;`" in "ToolboxChangeChannelDescription".

### CODE REVIEW

**Comment by YerongAI** [comment]
Hot reload is enabled, now you can open Office Tool Plus and check if anything wrong. Make sure you are connected to Internet.

**Comment by iDolmatov** [comment]
Yearly checked with /LoadDict. 
Unknow what the "Hot reload" you say. 
OTP autoupdate worked - update to latest 8.1.2.2. Language used internal, not automatic update from GitHub.

**Comment by YerongAI** [comment]
Hot reload means:
When you open Office Tool Plus, it will check content from Server, I uploaded your new translation to server, so it should automatically update content without any action.

**Comment by iDolmatov** [comment]
It's strange. Does not work.
Checked:
Launch;
Restart;
Upgrade from the old version and restart;
Checking the version of the program itself and restarting.
https://github.com/YerongAI/Office-Tool/blob/master/src/OfficeToolPlus/Style/Languages/ru-ru.xaml
`ToolboxRemoveOffice">Удаление Office</sys:String>`
image

**Comment by YerongAI** [comment]
I checked and it's work for me. Just open Office Tool Plus, switch to Toolbox page, and wait for automatically update.

**Comment by iDolmatov** [comment]
Worked in current time. 
I also clear `HKEY_CURRENT_USER\SOFTWARE\OfficeToolPlus`

**Comment by YerongAI** [comment]
Oh, you don't need to do any thing, this is automatically.

**Pull request merged**
