### PR TITLE
Translation 8.2.9.0 (Russian)

### PR DESCRIPTION
**Pull request by iDolmatov**
Hotkey can't by indicated, because translate the string without the hotkey letter.

### CODE REVIEW

**Comment by YerongAI** [comment]
Oh, that's okey.

**Comment by YerongAI** [comment]
Do you see that something like 'xxxx (I)'? I mean that put the hotkey to the end of string.

**Comment by iDolmatov** [comment]
I planned to write this, but did not dare. You can write this if it is consistent with other interface languages.

**Comment by YerongAI** [comment]
> I planned to write this, but did not dare. You can write this if it is consistent with other interface languages.

I don't know about Russian.

For Chinese, we always add hotkey like 'xxx (&amp;I)'

I think you can check hotkeys on Windows, so you can decide how to do.

**Comment by iDolmatov** [comment]
I see. Already updated.

**Comment by YerongAI** [comment]
I checked the hotkey on Windows in Russian, I see that Microsoft set hotkeys using English and Russian, it means that I must switch input method to execute the command. I never see anything like 'xxx (I)'.

**Comment by YerongAI** [comment]
If we can't understand the hotkey setting, I think we can remove the hotkey, which is better than setting a wrong one.

**Comment by iDolmatov** [comment]
Due to the differences between Cyrillic and Latin, different spellings are used in different programs. When translating, I often exclude hotkeys that are embedded in the letter of the word. If hotkeys are specified separately (in brackets or on the other side of the text), then I leave it.

Context menu (one point):
image
Tooltip:
image
For inline hints, the existing letter is used, if applicable at the program interface level. Windows "Win+X" menu (modification):
image

So it depends on the design where the hotkey is specified. In the translation under discussion, I would prefer to avoid ambiguity. A simple option would be to remove the "hidden" hint, a more difficult option would be to adjust hotkeys to the layout / translation of the interface.

**Comment by YerongAI** [comment]
So it's better to remove the hotkey?

**Comment by iDolmatov** [comment]
Let it be removed.

**Pull request merged**
