### PR TITLE
Update th-th.xaml

### PR DESCRIPTION
**Pull request by OllyMaster**

### CODE REVIEW

**Review by YerongAI — CHANGES_REQUESTED** [review]
`DeployPinIconToTaskbar` is incorrect, there is no Windows 10 or 11, just 7, 8 and 8.1.

**Review by YerongAI — APPROVED** [review]

**Comment by OllyMaster** [comment]
okay I understand At first I thought your program would support Windows 10 and 11.

**Comment by YerongAI** [comment]
> okay I understand At first I thought your program would support Windows 10 and 11.

The function is provided by Microsoft, not me.

**Comment by OllyMaster** [comment]
okey i'm motivation for your team I may be just a small part of your program development. But I'm happy to help ^_^

**Pull request merged**
