### PR TITLE
Rebuild LICENSE

### PR DESCRIPTION
**Pull request by YerongAI**
For some reasons we would like to change the LICENSE of this repository in order to better provide a wider range of services. The `LICENSE` change will not affect other files, and we hope that you can approve to it. Thank you!

### CODE REVIEW

**Comment by akio1321** [comment]
Agree

iPhoneから送信

2023/12/07 9:54、Yerong ***@***.***>のメール:

﻿

@chiyi4488<https://github.com/chiyi4488> @dekthaiinchina<https://github.com/dekthaiinchina> @igorruckert<https://github.com/igorruckert> @akio1321<https://github.com/akio1321> @VenusGirl<https://github.com/VenusGirl> @Berny23<https://github.com/Berny23> @AnomSanjaya<https://github.com/AnomSanjaya> @iDolmatov<https://github.com/iDolmatov> @yaeyaya<https://github.com/yaeyaya>

**Comment by VenusGirl** [comment]
Agree

**Review by iDolmatov — APPROVED** [review]

**Comment by YerongAI** [comment]
> I see no reason to refuse. Currently the repository is localized (by third parties), so changing the license type should not be a problem. The updated license does not restrict the distribution and modification of translations.
> 
> However, if this applies to the entire product (OTP), then check the terms of distribution. For example, the implied context is about the sale of a copy of the program by any person, as well as modification of the software.
> 
> > The LICENSE change will not affect other files
> 
> You can clarify what exactly the license covers. Without this, the paragraph above would have turned out.

Thank you for this info. Now I should understand that the `LICENSE` only apply to this translations, not Office Tool Plus itself. When users run Office Tool Plus at first time, they will be asked for accepting a Use Terms, instead of the `LICENSE`. I think the two should be unrelated.

That's how I understand it, please point out if there are any problems.

**Review by iDolmatov — COMMENTED** [review]
Pay attention to this. Is your license option consistent with the original Microsoft license? The original license may prohibit the listed actions, and the text of the license does not include a clause about borrowing other people's materials.

**Comment by YerongAI** [comment]
> > Note: I don't suggest anyone to change preferences data! This data is provided by Microsoft.
> 
> Pay attention to this. Is your license option consistent with the original Microsoft license? The original license may prohibit the listed actions, and the text of the license does not include a clause about borrowing third-party objects.

The applications preferences was collected from MS server, not a public zone. Maybe I should not upload the json here?

**Comment by iDolmatov** [comment]
I'm not familiar with the intricacies of licensing relationships, particularly with GitHub. Therefore, be sure to study all the nuances so as not to find yourself in litigation with Microsoft and/or GitHub.

The source code of the program is closed, but, as I understand it, checking for updates is associated with your domain (not GitHub). Therefore, transferring non-editable data to its source can eliminate a license conflict, although it will transfer the load to another source of files.

**Comment by Berny23** [comment]
I agree to the change.

**Comment by YerongAI** [comment]
> i dont know if LICENSE will affected to me, since i didn't really care about that

In fact, change LICENSE will not make any effects on you. You can also modify translations, or do anything you did before.

If you agree the change, please let me know.

**Comment by dekthaiinchina** [comment]
_I agree with this license change. If there is no impact on the creators and users of this program._

**Review by chiyi4488 — COMMENTED** [review]
I'd like to understand why you want to change your License. What is your motivation?

我想理解為何你想變更授權許可書。你的動機是什麼。

**Comment by YerongAI** [comment]
> I'd like to understand why you want to change your License. What is your motivation?
> 
> 我想理解為何你想變更授權許可書。你的動機是什麼。

不变更会不符合镜像站的协议约束，会导致无法上传到镜像站服务

**Review by chiyi4488 — APPROVED** [review]

**Pull request merged**
