### PR TITLE
My contribution for community, I've tested successfully and you can check again. Thanks alot.

### PR DESCRIPTION
**Pull request by phuocding**
I add filename 'vi-vn.xaml' to the folder without an open solution in visual studio normally. I want to replace background by my countryside flag but I cannot open solution to test. I wish you could develop for me. Thank you one more time.

### CODE REVIEW

**Comment by YerongAI** [comment]
> I add filename 'vi-vn.xaml' to the folder without an open solution in visual studio normally. I want to replace background by my countryside flag but I cannot open solution to test. I wish you could develop for me. Thank you one more time.

Hi,
Thanks for your work.
But I can't understand why you want to replace background by your countryside flag.

**Comment by chiyi4488** [comment]
Background settings should not be in Github, which must be set using Office Tool Admin Center.
擷取

**Comment by phuocding** [comment]
Oh, I've checked in Chinese language and I saw the background image. I also
want to replace for impressive. Maybe don't need anymore. Thank you.
-- 

*  •  **NGUYEN DINH PHUOC*
*  •  Developer*
*  •  *+84 969 426 341
*  • * phuocding@gmail.com

**Comment by chiyi4488** [comment]
Sorry, my English is not good.XD

**Pull request merged**
