### PR TITLE
New translation for pt-br

### PR DESCRIPTION
**Pull request by vinibudd**

### CODE REVIEW

**Comment by chiyi4488** [comment]
I am sorry to let you wait so long, but I don't have permission to review (because I am just a translator in Traditional Chinese), please wait for the author's response, thank you.

**Comment by vinibudd** [comment]
I am the author, I am updating small errors that in the translation I did not see

**Comment by chiyi4488** [comment]
I mean the author of the program.😂😂

**Comment by vinibudd** [comment]
Got it

**Comment by vinibudd** [comment]
I updated the translation pt-br and so far it was not reflected in the program

**Comment by YerongAI** [comment]
> I updated the translation pt-br and so far it was not reflected in the program

Sorry about that, I don't know why my email client was stopped and I didn't received any notification. I will apply your new translation as soon as possible. Thanks for your great job!

**Comment by vinibudd** [comment]
@YerongAI I noticed that you changed the writing of the languages in "Portuguese" you change to "Portuguese (BR), it gets better and it differs with Portugal

**Comment by YerongAI** [comment]
> @YerongAI I noticed that you changed the writing of the languages in "Portuguese" you change to "Português (BR), it gets better and it differs with Portugal

All done, I changed it to Portuguese (BR), but I didn't release now, I will published it later.

**Pull request closed without merging**
